# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["xhci_pci" "ahci" "nvme" "usb_storage" "sd_mod"];
  boot.initrd.kernelModules = ["dm-snapshot"];
  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];
  boot.initrd.luks.devices = {
    "enc" = {
      device = "/dev/disk/by-uuid/0f39ca55-877e-4686-99fa-9c0e71bb2647";
      preLVM = true;
      allowDiscards = true;
    };
  };

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/0d60a50c-2bdb-493c-8126-4a7308fdd360";
    fsType = "btrfs";
    options = ["subvol=root" "compress=zstd:9" "noatime"];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/0d60a50c-2bdb-493c-8126-4a7308fdd360";
    fsType = "btrfs";
    options = ["subvol=nix" "compress-force=zstd:9" "noatime"];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/0d60a50c-2bdb-493c-8126-4a7308fdd360";
    fsType = "btrfs";
    options = ["subvol=home" "compress=zstd:9"];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/FB1B-5B29";
    fsType = "vfat";
  };

  # External hdd
  fileSystems."/run/media/marmar/Tina" = {
    device = "/dev/disk/by-uuid/72fecad1-0cd2-4f92-961c-aa08a8fc7372";
    fsType = "btrfs";
    options = [ "compress-force=zstd:15" "noauto" "autodefrag" ];
    neededForBoot = false;
  };

  fileSystems."/run/media/marmar/Datasets" = {
    device = "/dev/disk/by-uuid/b95edda2-a5b1-4ace-998f-d21b6230ee7f";
    fsType = "btrfs";
    options = [ "compress-force=zstd:15" "noauto" "autodefrag" ];
    neededForBoot = false;
  };

  swapDevices = [
    {device = "/dev/disk/by-uuid/d7f2e43d-2734-4314-88bc-1ddb0fbc31fa";}
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp3s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlo1.useDHCP = lib.mkDefault true;

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  # Set your system kind (for flakes)
  nixpkgs.hostPlatform = "x86_64-linux";
}
