name: "Test for nix build"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v20
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - run: sudo nixos-rebuild boot --flake .#roguenix
    - run: nix flake check
